{ config, pkgs, lib, userState, ... }:

{
  # Cafaye Foundation
  imports = [
    ./local-user.nix # Generated by installer
    
    # Interface & Editors
    ./modules/interface/terminal.nix
    ./modules/interface/tools.nix
    ./modules/interface/theme.nix
    ./modules/interface/cli.nix
    ./modules/editors/neovim.nix
    ./modules/editors/helix.nix
    
    # Core Infrastructure
    ./modules/core/sops.nix
    ./modules/core/tailscale.nix
    ./modules/core/vps.nix
    ./modules/core/monitoring.nix
    
    # Optional Stacks (Managed via sub-imports)
    ./modules/languages
    ./modules/services
    ./modules/frameworks
  ];

  # Home Manager needs a bit of info to work
  home.packages = with pkgs; [
    # Foundation tools
    git
    curl
    jq
    gum
    yq-go # Portable YAML parsing for workspace config
    ripgrep
    fd
    bat
    fzf
  ];

  home.sessionVariables = {
    EDITOR = lib.mkForce (userState.editors.default or "nvim");
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;
  
  # State Version (managed by installer usually, but fallback here)
  home.stateVersion = lib.mkDefault "24.11";
}
