{ config, pkgs, lib, userState, ... }:

let
  enabled = userState.interface.terminal.multiplexer.tmux.enable or true;
  
  # Helper to read optional config files
  readConfig = path: if builtins.pathExists path then builtins.readFile path else "";
  
  # Configuration layers
  defaultConfig = readConfig ../../../config/cafaye/tmux/tmux.conf;
  userConfig = readConfig ../../../config/user/tmux/tmux.conf;
in
{
  config = lib.mkIf enabled {
    programs.tmux = {
      enable = true;
      shell = "${pkgs.zsh}/bin/zsh";
      historyLimit = 50000;
      mouse = true;
      extraConfig = ''
        # ═══════════════════════════════════════════════════════════════════
        # CAFAYE TMUX CONFIGURATION
        # Managed by Nix/Home Manager - DO NOT EDIT THIS FILE DIRECTLY
        # ═══════════════════════════════════════════════════════════════════
        
        # --- [ LAYER 1: CAFAYE DEFAULTS ] ---
        ${defaultConfig}
        
        # --- [ LAYER 2: USER OVERRIDES ] ---
        ${userConfig}
      '';
    };

    # Link the theme script to the expected location
    xdg.configFile."tmux/base16.sh".source = ../../../config/user/tmux/base16.sh;
    xdg.configFile."tmux/tmux-256color-italic.terminfo".source = ../../../config/user/tmux/tmux-256color-italic.terminfo;

    # Ensure TPM/plugins exist so resurrect+continuum are functional on first run.
    home.activation.cafayeTmuxPlugins = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      TPM_DIR="$HOME/.tmux/plugins/tpm"
      if [ ! -d "$TPM_DIR/.git" ]; then
        run ${pkgs.git}/bin/git clone https://github.com/tmux-plugins/tpm "$TPM_DIR" >/dev/null 2>&1 || true
      fi
      if [ ! -d "$HOME/.tmux/plugins/tmux-resurrect/.git" ]; then
        run ${pkgs.git}/bin/git clone https://github.com/tmux-plugins/tmux-resurrect "$HOME/.tmux/plugins/tmux-resurrect" >/dev/null 2>&1 || true
      fi
      if [ ! -d "$HOME/.tmux/plugins/tmux-continuum/.git" ]; then
        run ${pkgs.git}/bin/git clone https://github.com/tmux-plugins/tmux-continuum "$HOME/.tmux/plugins/tmux-continuum" >/dev/null 2>&1 || true
      fi
      if [ -x "$TPM_DIR/bin/install_plugins" ]; then
        run "$TPM_DIR/bin/install_plugins" >/dev/null 2>&1 || true
      fi
    '';

    # Ensure tmux italic-capable terminfo exists on every host.
    home.activation.cafayeTmuxTerminfo = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      if command -v ${pkgs.ncurses}/bin/tic >/dev/null 2>&1; then
        mkdir -p "$HOME/.terminfo"
        if ! infocmp tmux-256color-italic >/dev/null 2>&1; then
          run ${pkgs.ncurses}/bin/tic -x -o "$HOME/.terminfo" "$HOME/.config/tmux/tmux-256color-italic.terminfo" >/dev/null 2>&1 || true
        fi
      fi
    '';
  };
}
